[build]
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/server/socket.io/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "public"

