[build]
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/socket.io/*"
  to = "http://localhost:3000/socket.io/:splat"
  status = 200
  force = true

[dev]
  framework = "#custom"
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "public"